### ISSUE TITLE
Missing CelebA checkpoint

### ISSUE THREAD

**Issue by cobalamin** [bahjat-kawar/ddrm-jpeg#2]
Hi there,
many thanks for making your code publicly available! I wanted to try out the model for CelebAHQ restoration, but ran into the issue that the checkpoint URL you have in [your code](https://github.com/bahjat-kawar/ddrm-jpeg/blob/master/runners/diffusion.py#L113) is unavailable (Access Denied). The URL in question: https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt

It would be great if you could provide an updated URL for a checkpoint :) Cheers!

**Comment by bahjat-kawar** [comment]
The CelebA-HQ checkpoint was taken from [SDEdit](https://github.com/ermongroup/SDEdit). If there is an access denied issue, please contact the original authors of SDEdit.
