### ISSUE TITLE
Missing exp/imagenet_val_1k.txt

### ISSUE THREAD

**Issue by cobalamin** [bahjat-kawar/ddrm-jpeg#3]
When running the example call in the README.md `python main.py --ni --config imagenet_256.yml --doc imagenet -i imagenet --deg jpeg80 --num_avg_samples 8`, I run into the following error:

```
  File "ddrm-jpeg/datasets/imagenet_subset.py", line 75, in __init__
    with open(meta_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/imagenet_val_1k.txt'
```

This file is mentioned in the README here: https://github.com/bahjat-kawar/ddrm-jpeg/blob/master/README.md?plain=1#L44, but not provided with the repository, and does not seem to be generated by any code in the repository. It seems this file was not committed to the repo. Am I missing something?

**Comment by bahjat-kawar** [comment]
The list can be found here: https://github.com/XingangPan/deep-generative-prior/blob/master/scripts/imagenet_val_1k.txt

**Comment by cobalamin** [comment]
Thank you!
